[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
NATS_URL = "nats://htpi-nats.railway.internal:4222"
NATS_USER = "${{NATS_USER}}"
NATS_PASSWORD = "${{NATS_PASSWORD}}"